### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by xymb-endcrystalme** [xymb-endcrystalme/LinearRegionFileFormatTools#1]

**Comment by xymb-endcrystalme** [comment]
Pull requests are welcome.

**Comment by ghost** [comment]
it works on windows, you need to add this marks
![Screenshot_1](https://github.com/xymb-endcrystalme/LinearRegionFileFormatTools/assets/108226177/b239565a-9385-42ee-bc49-63be3bfb7496)
![image](https://github.com/xymb-endcrystalme/LinearRegionFileFormatTools/assets/108226177/e79e4fcd-8d39-4391-acb1-6f7cedf31d04)
@xymb-endcrystalme
