### ISSUE TITLE
I'm getting this error when moving my world

### ISSUE THREAD

**Issue by PedroMPagani** [xymb-endcrystalme/LinearRegionFileFormatTools#19]
Traceback (most recent call last):
  File "./convert_region_files.py", line 45, in convert_file
    region = open_region_anvil(source_file)
  File "/var/lib/pterodactyl/volumes/1d41fcc3-af9e-4e3c-8903-1ff648e45929/linear.py", line 194, in open_region_anvil
    raise Exception("Compression type %d unimplemented!" % (compression_type))

**Comment by PedroMPagani** [comment]
https://cdn.discordapp.com/attachments/1183053853097213984/1241123159210590288/r.62.-124.mca?ex=66490d84&is=6647bc04&hm=a7268d03292cd4a9e90881c039e46e09421a2f6ae3633a111e429b6b5c3c055a&
maybe this link works for the region file

**Comment by PedroMPagani** [comment]
I think it's due my overworld being compressed with GZIP instead of Zlib

**Comment by PedroMPagani** [comment]
Would you be able to add GZIP reading too?

**Comment by PedroMPagani** [comment]
I'm willing to pay for this addon :(, I have like 4TB of data world and it's all on GZIP, it would be almost impossible for me to reload everything to convert it to the zlib format

**Comment by PedroMPagani** [comment]
@xymb-endcrystalme

**Comment by xymb-endcrystalme** [comment]
You're most likely using the new zstd chunk format? I'll add zstd to my TODO list.
