### ISSUE TITLE
Corruption on server crash

### ISSUE THREAD

**Issue by icicle85** [xymb-endcrystalme/LinearRegionFileFormatTools#20]
As the title says, chunks will not save properly if the server were to crash, and unlike with mca, where if the server crashes the furthest it can rollback is the last autosave (less than 5 mins), when using the .linear format event after waiting a long time, abruptly stopping the server leads to chunk save errors and rollbacks from much further back than 5 minutes. Also playerdata is unaffected, leading to some interesting scenarios where items are duped/lost.

**Comment by xymb-endcrystalme** [comment]
What fork are you using?

**Comment by icicle85** [comment]
> What fork are you using?

I tried using leaves and then leaf, both supporting linear, but the problem persists with both

**Comment by xymb-endcrystalme** [comment]
What filesystem are you using?

**Comment by xymb-endcrystalme** [comment]
Oh, your problem is that rollbacks are further in the past! Filesystem doesn't matter.

I am working on `Linear v2` that won't have as much of a problem with rollbacks. 👍

ETA about a week.
