### ISSUE TITLE
Bug: The world was reset after the transformation

### ISSUE THREAD

**Issue by wling-art** [xymb-endcrystalme/LinearRegionFileFormatTools#21]
I was using the tool to convert the region to .liner format after deleting the .mca from the old format I noticed that when I reopened the server, the world would turn back to the way it was, no sign of construction at all.
I'm using the **leaves** end with the .liner storage format turned on, but I converted it manually using the tool here.
So wondering what went wrong here.

**Comment by xymb-endcrystalme** [comment]
DM me on Discord if you want me to take a look closer look, Github isn't suited for direct technical support.
I'm pretty certain it's not a problem with either leaves nor linear, but with configuration.
